# Generated by Django 4.1.7 on 2023-04-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Должность')),
                ('short_name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Сокращенная версия')),
                ('note', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Дополнительная информация')),
                ('sort', models.CharField(blank=True, default=0, max_length=5, verbose_name='Позиция при сортировке')),
                ('hash', models.CharField(blank=True, default='', max_length=200, verbose_name='Hash')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('hash',), name='staff_position_hash_unique'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.CheckConstraint(check=models.Q(('name__length__gt', 0)), name='staff_position_name_not_empty'),
        ),
    ]
